version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0.12-node-browsers
    environment:
      CC_TEST_REPORTER_ID: d5bd47e1f470452cfdfed17f51f8d4926d56ea96a170cc4ae61ac3bf0737210f
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: 
          name: Run Composer Install
          command: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: 
          name: Run PHPUnit Tests
          command: ./vendor/bin/phpunit
          environment: 
              XDEBUG_MODE: coverage
      - run:
          name: Run CC Test Reporter after-build
          command: ./cc-test-reporter after-build -t clover
