name: CI

on:
  push:
    branches: [ "phpunit-version-v7" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v7
        with:
          configuration: test/phpunit.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "test/**/*.xml"
